import {useState} from "react";
import {api,saveSession} from "../api.js";
import {t} from "../i18n.js";
import LanguageToggle from "./LanguageToggle.jsx";
export default function AuthModal({onClose,onLogin}){
 const [mode,setMode]=useState("login"),[show,setShow]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false),[form,setForm]=useState({name:"",email:"",password:"",confirm:"",location:""});
 async function submit(e){e.preventDefault();setError("");if(mode==="register"&&form.password!==form.confirm){setError(t.passwordMismatch);return;}setLoading(true);try{if(mode==="login"){const x=await api.login({email:form.email,password:form.password});saveSession(x.token,x.user);onLogin(x.user);}else{const x=await api.register({name:form.name,email:form.email,password:form.password,role:"customer",location:form.location||null});if(x.pending){setError(x.message);setMode("login");}else{saveSession(x.token,x.user);onLogin(x.user);}}}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div className="auth-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="auth-modal"><div style={{display:"flex",justifyContent:"flex-end",marginBottom:8}}><LanguageToggle compact /></div><button className="modal-close" onClick={onClose}>×</button><img src="/logo.png" className="modal-logo" alt="Taja Farm"/><h2>{mode==="login"?t.login:t.createAccount}</h2>{error&&<p className="auth-error">{error}</p>}<form onSubmit={submit}>{mode==="register"&&<><label>{t.fullName}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>{t.profileLocation}<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></>}<label>{t.email}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>{t.password}<div className="password-row"><input type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button type="button" onClick={()=>setShow(!show)}>{show?"🙈":"👁"}</button></div></label>{mode==="register"&&<label>{t.confirmPassword}<input type={show?"text":"password"} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} required/></label>}<button className="btn btn-primary btn-full" disabled={loading}>{loading?t.saving:mode==="login"?t.login:t.signUp}</button></form><p className="auth-switch">{mode==="login"?t.noAccount:t.alreadyHaveAccount} <button onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?t.signUp:t.login}</button></p></div></div>
}
