using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using TajaFarm.Api.Data;using TajaFarm.Api.Models;
namespace TajaFarm.Api.Controllers;
[ApiController][Route("api/admin")]
public class AdminController:BaseController
{
 [HttpGet("stats")]public async Task<IActionResult> Stats([FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;return Ok(new{totalUsers=await db.Users.CountAsync(),totalFarmers=await db.Users.CountAsync(x=>x.Role=="farmer"&&x.IsApproved),pendingFarmers=await db.Users.CountAsync(x=>x.Role=="farmer"&&!x.IsApproved),totalCustomers=await db.Users.CountAsync(x=>x.Role=="customer"),totalProducts=await db.Products.CountAsync(),totalOrders=await db.Orders.CountAsync()});}
 [HttpGet("users")]public async Task<IActionResult> Users([FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var users=await db.Users.OrderByDescending(x=>x.CreatedAt).ToListAsync();return Ok(users.Select(UserDto));}
 [HttpGet("pending-farmers")]public async Task<IActionResult> Pending([FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var users=await db.Users.Where(x=>x.Role=="farmer"&&!x.IsApproved).ToListAsync();return Ok(users.Select(UserDto));}
 [HttpPut("farmers/{id:int}/approval")]public async Task<IActionResult> Approval(int id,ApprovalRequest req,[FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var u=await db.Users.FindAsync(id);if(u is null||u.Role!="farmer")return NotFound();u.IsApproved=req.Approved;await db.SaveChangesAsync();return Ok(UserDto(u));}
 [HttpGet("products")]public async Task<IActionResult> Products([FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var ps=await db.Products.ToListAsync();var f=await db.Users.ToDictionaryAsync(x=>x.Id,x=>x.Name);return Ok(ps.Select(x=>new{x.Id,x.Name,x.Category,x.Price,x.CostPrice,x.Stock,x.ExpiryDate,x.ImageUrl,farmerName=f.GetValueOrDefault(x.FarmerId,"—")}));}
 [HttpDelete("products/{id:int}")]public async Task<IActionResult> DeleteProduct(int id,[FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var p=await db.Products.FindAsync(id);if(p is null)return NotFound();db.Products.Remove(p);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("orders")]public async Task<IActionResult> Orders([FromServices]AppDbContext db){var r=RequireRole("admin",out _);if(r is not null)return r;var os=await db.Orders.Include(x=>x.Items).OrderByDescending(x=>x.CreatedAt).ToListAsync();return Ok(os.Select(BaseController.OrderDto));}
 [HttpPut("orders/{id:int}/status")]public async Task<IActionResult> Status(int id,AdminOrderStatusRequest req,[FromServices]AppDbContext db){var r=RequireRole("admin",out var t);if(r is not null)return r;if(!OrderTracking.IsValid(req.Stage))return BadRequest(new{error="Invalid stage"});var o=await db.Orders.FindAsync(id);if(o is null)return NotFound();if(!o.FarmerConfirmed&&req.Stage!="placed")return BadRequest(new{error="Farmer must confirm the order before admin can change delivery status."});o.ManualStage=req.Stage;o.Status=req.Stage;await db.SaveChangesAsync();db.Notifications.Add(new Notification{UserId=o.CustomerId,Title="डेलिभरी अपडेट",Message=$"अर्डर #{o.Id} को स्थिति '{req.Stage}' भएको छ।",Type="order_status",RelatedId=o.Id});await db.SaveChangesAsync();return Ok(new{message="Status updated",order=BaseController.OrderDto(o)});}
}
