using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using TajaFarm.Api.Data;using TajaFarm.Api.Models;
namespace TajaFarm.Api.Controllers;[ApiController][Route("api/messages")]
public class MessagesController:BaseController{
 [HttpPost]public async Task<IActionResult> Send(MessageRequest req,[FromServices]AppDbContext db){var r=RequireUser(out var t);if(r is not null)return r;var p=await db.Products.FindAsync(req.ProductId);if(p is null)return NotFound();var u=await db.Users.FindAsync(t!.Id);var m=new Message{FromUserId=t.Id,FromName=u!.Name,ToUserId=p.FarmerId,ProductId=p.Id,ProductName=p.Name,Text=req.Text};db.Messages.Add(m);await db.SaveChangesAsync();return StatusCode(201,m);}
 [HttpGet("inbox")]public async Task<IActionResult> Inbox([FromServices]AppDbContext db){var r=RequireRole("farmer",out var t);if(r is not null)return r;return Ok(await db.Messages.Where(x=>x.ToUserId==t!.Id).OrderByDescending(x=>x.CreatedAt).ToListAsync());}
 [HttpGet("sent")]public async Task<IActionResult> Sent([FromServices]AppDbContext db){var r=RequireUser(out var t);if(r is not null)return r;return Ok(await db.Messages.Where(x=>x.FromUserId==t!.Id).OrderByDescending(x=>x.CreatedAt).ToListAsync());}
 [HttpGet("mine")]public async Task<IActionResult> Mine([FromServices]AppDbContext db){var r=RequireUser(out var t);if(r is not null)return r;return Ok(await db.Messages.Where(x=>x.FromUserId==t!.Id||x.ToUserId==t.Id).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,x.FromUserId,x.FromName,x.ToUserId,x.ProductId,x.ProductName,x.Text,x.CreatedAt,isMine=x.FromUserId==t.Id}).ToListAsync());}
 [HttpPost("reply")]public async Task<IActionResult> Reply(MessageReplyRequest req,[FromServices]AppDbContext db){var r=RequireRole("farmer",out var t);if(r is not null)return r;var u=await db.Users.FindAsync(t!.Id);var p=await db.Products.FindAsync(req.ProductId);var m=new Message{FromUserId=t.Id,FromName=u!.Name,ToUserId=req.ToUserId,ProductId=req.ProductId,ProductName=p?.Name,Text=req.Text};db.Messages.Add(m);await db.SaveChangesAsync();return StatusCode(201,m);}
}
