using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using TajaFarm.Api.Data;using TajaFarm.Api.Models;
namespace TajaFarm.Api.Controllers;
[ApiController][Route("api/orders")]
public class OrdersController:BaseController
{
 private async Task<(Order? order,string? error)> CreateOrder(int customerId,string customerName,int productId,int qty,string payment,AppDbContext db){if(qty<=0)return(null,"Quantity must be greater than 0");var p=await db.Products.FindAsync(productId);if(p is null)return(null,"Product not found");if(p.Stock<qty)return(null,$"Not enough stock for {p.Name}");if(p.ExpiryDate.HasValue&&p.ExpiryDate.Value.Date<DateTime.UtcNow.Date)return(null,$"{p.Name} is expired");p.Stock-=qty;var o=new Order{CustomerId=customerId,CustomerName=customerName,PaymentMethod=string.IsNullOrWhiteSpace(payment)?"cod":payment,Status="pending_farmer_confirmation",ManualStage="placed",FarmerConfirmed=false};o.Items.Add(new OrderItem{ProductId=p.Id,ProductName=p.Name,Qty=qty,Price=p.Price,CostPrice=p.CostPrice,FarmerId=p.FarmerId});o.Total=p.Price*qty;db.Orders.Add(o);await db.SaveChangesAsync();db.Notifications.Add(new Notification{UserId=p.FarmerId,Title="नयाँ अर्डर",Message=$"'{p.Name}' को नयाँ अर्डर आएको छ। पुष्टि गर्नुहोस्।",Type="new_order",RelatedId=o.Id});await db.SaveChangesAsync();return(o,null);}
 [HttpPost("buy-now")]
 public async Task<IActionResult> BuyNow(BuyNowRequest req,[FromServices]AppDbContext db){var r=RequireRole("customer",out var t);if(r is not null)return r;var (o,e)=await CreateOrder(t!.Id,t!.Role=="customer"? (await db.Users.FindAsync(t.Id))!.Name:"",req.ProductId,req.Qty,req.PaymentMethod,db);return e!=null?BadRequest(new{error=e}):StatusCode(201,OrderDto(o!));}
 [HttpPost("checkout")]
 public async Task<IActionResult> Checkout(CheckoutRequest req,[FromServices]AppDbContext db){var r=RequireRole("customer",out var t);if(r is not null)return r;var u=await db.Users.FindAsync(t!.Id);var cart=await db.CartItems.Where(x=>x.UserId==t.Id).ToListAsync();if(cart.Count==0)return BadRequest(new{error="Cart is empty"});var o=new Order{CustomerId=t.Id,CustomerName=u!.Name,PaymentMethod=req.PaymentMethod,Status="pending_farmer_confirmation",ManualStage="placed"};foreach(var c in cart){var p=await db.Products.FindAsync(c.ProductId);if(p is null)continue;if(c.Qty<=0||p.Stock<c.Qty)return BadRequest(new{error=$"Not enough stock for {p?.Name??"product"}"});if(p.ExpiryDate.HasValue&&p.ExpiryDate.Value.Date<DateTime.UtcNow.Date)return BadRequest(new{error=$"{p.Name} is expired"});p.Stock-=c.Qty;o.Items.Add(new OrderItem{ProductId=p.Id,ProductName=p.Name,Qty=c.Qty,Price=p.Price,CostPrice=p.CostPrice,FarmerId=p.FarmerId});o.Total+=p.Price*c.Qty;}if(o.Items.Count==0)return BadRequest(new{error="No valid products in cart"});db.Orders.Add(o);db.CartItems.RemoveRange(cart);await db.SaveChangesAsync();foreach(var farmerId in o.Items.Select(x=>x.FarmerId).Distinct())db.Notifications.Add(new Notification{UserId=farmerId,Title="नयाँ अर्डर",Message=$"अर्डर #{o.Id} मा तपाईंको उत्पादन छ। पुष्टि गर्नुहोस्।",Type="new_order",RelatedId=o.Id});await db.SaveChangesAsync();return StatusCode(201,OrderDto(o));}
 [HttpGet("mine")]
 public async Task<IActionResult> Mine([FromServices]AppDbContext db){var r=RequireRole("customer",out var t);if(r is not null)return r;var os=await db.Orders.Include(x=>x.Items).Where(x=>x.CustomerId==t!.Id).OrderByDescending(x=>x.CreatedAt).ToListAsync();return Ok(os.Select(OrderDto));}
 [HttpGet("{id:int}")]
 public async Task<IActionResult> GetOne(int id,[FromServices]AppDbContext db){var r=RequireUser(out var t);if(r is not null)return r;var o=await db.Orders.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==id);if(o is null)return NotFound();if(o.CustomerId!=t!.Id&&t.Role!="admin"&&!(t.Role=="farmer"&&o.Items.Any(i=>i.FarmerId==t.Id)))return StatusCode(403);return Ok(OrderDto(o));}
 [HttpGet("farmer/mine")]
 public async Task<IActionResult> FarmerOrders([FromServices]AppDbContext db){var r=RequireRole("farmer",out var t);if(r is not null)return r;var os=await db.Orders.Include(x=>x.Items).Where(x=>x.Items.Any(i=>i.FarmerId==t!.Id)).OrderByDescending(x=>x.CreatedAt).ToListAsync();return Ok(os.Select(o=>new{ o.Id,o.CustomerName,o.CreatedAt,o.Total,o.FarmerConfirmed,o.Status,stage=o.FarmerConfirmed?o.ManualStage:"placed",items=o.Items.Where(i=>i.FarmerId==t!.Id)}));}
 [HttpPost("{id:int}/confirm")]
 public async Task<IActionResult> Confirm(int id,[FromServices]AppDbContext db){var r=RequireRole("farmer",out var t);if(r is not null)return r;var o=await db.Orders.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==id);if(o is null)return NotFound();if(!o.Items.Any(i=>i.FarmerId==t!.Id))return StatusCode(403);if(o.FarmerConfirmed)return Ok(OrderDto(o));o.FarmerConfirmed=true;o.Status="confirmed";o.ManualStage="confirmed";await db.SaveChangesAsync();db.Notifications.Add(new Notification{UserId=o.CustomerId,Title="अर्डर पुष्टि भयो",Message=$"अर्डर #{o.Id} किसानले पुष्टि गर्नुभयो।",Type="order_status",RelatedId=o.Id});await db.SaveChangesAsync();return Ok(OrderDto(o));}
}
