const NE = {
  brandName:"ताजा Farm", brandTagline:"किसानदेखि उपभोक्तासम्म",
  welcomeBack:"फेरि स्वागत छ!", loginSubtitle:"जारी राख्न लगइन गर्नुहोस्", customer:"ग्राहक", farmer:"किसान", admin:"एडमिन",
  emailOrPhone:"इमेल वा फोन नम्बर", emailPlaceholder:"आफ्नो इमेल वा फोन नम्बर लेख्नुहोस्", password:"पासवर्ड", passwordPlaceholder:"पासवर्ड लेख्नुहोस्", forgotPassword:"पासवर्ड बिर्सनुभयो?", login:"लगइन", loggingIn:"लगइन हुँदैछ...",
  demoAccountNote:"डेमो खाताहरू — ग्राहक: customer@tajafarm.com / customer123 · किसान: farmer@tajafarm.com / farmer123 · एडमिन: admin@tajafarm.com / admin123",
  noAccount:"खाता छैन?", signUp:"साइन अप गर्नुहोस्", areYouFarmer:"तपाईं किसान हुनुहुन्छ?", registerHere:"यहाँ दर्ता गर्नुहोस्", heroTitle1:"खेतबाट", heroTitle2:"घरपरिवारसम्म", heroSubtitle:"ताजा, स्वस्थ र प्राकृतिक उत्पादन किसानबाट सिधै तपाईंको घरसम्म।", stat1Top:"१००%",stat1Bottom:"ताजा",stat2Top:"सिधै",stat2Bottom:"किसानबाट",stat3Top:"स्वस्थ",stat3Bottom:"र प्राकृतिक", feat1:"१००% ताजा",feat2:"किसानबाट सिधै",feat3:"स्वस्थ र प्राकृतिक",
  navHome:"गृहपृष्ठ",navOrders:"मेरा अर्डरहरू",navWishlist:"मनपर्ने सूची",navProfile:"मेरो प्रोफाइल",navMessages:"सन्देशहरू",navLogout:"लगआउट",
  searchPlaceholder:"तरकारी, फलफूल, अन्न खोज्नुहोस्...",
  heroBannerTitle1:"तपाईंले पाउनुपर्ने ताजापन,",heroBannerTitle2:"तपाईंले विश्वास गर्ने किसानबाट",heroBannerSub:"हातले टिपिएको, रसायनरहित र मौसमी उत्पादन तपाईंको ढोकैमा।",shopNow:"अहिले किन्नुहोस्",feature1Title:"किसानबाट सिधै",feature1Sub:"बिचौलिया छैन",feature2Title:"ताजा र गुणस्तर",feature2Sub:"१००% गुणस्तरीय उत्पादन",feature3Title:"सुरक्षित भुक्तानी",feature3Sub:"सुरक्षित र भरपर्दो",feature4Title:"छिटो डेलिभरी",feature4Sub:"समयमै डेलिभरी",
  shopByCategories:"श्रेणी अनुसार किनमेल",viewAll:"सबै हेर्नुहोस्",topPicks:"तपाईंका लागि उत्तम छनोट",addToCart:"कार्टमा राख्नुहोस्",added:"थपियो ✓",loadingProducts:"उत्पादनहरू लोड हुँदैछ...",loadFailedNote:"— ब्याकइन्ड चलिरहेको छ?",
  quantity:"परिमाण",buyNow:"अहिले किन्नुहोस्",deliveredBy:"डेलिभरी गर्ने",deliveryTime:"डेलिभरी समय",shipping:"ढुवानी",freeShippingNote:"रु. ५०० भन्दा माथिको अर्डरमा निःशुल्क",productDetails:"उत्पादन विवरण",aboutFarmer:"किसानको बारेमा",viewFarmProfile:"फार्म प्रोफाइल हेर्नुहोस्",alsoLike:"तपाईंलाई यो पनि मन पर्न सक्छ",badgeOrganic:"१००% जैविक",badgePesticideFree:"कीटनाशकरहित",badgeHandPicked:"हातले टिपिएको",badgeFreshNatural:"ताजा र प्राकृतिक",category:"श्रेणी",price:"मूल्य",stock:"स्टक",stockAvailable:"उपलब्ध",loadingProduct:"उत्पादन लोड हुँदैछ...",home:"गृहपृष्ठ",localFarmer:"स्थानीय किसान",
  contactFarmer:"किसानलाई सम्पर्क गर्नुहोस्",messagePlaceholder:"आफ्नो प्रश्न यहाँ लेख्नुहोस् (जस्तै: डेलिभरी समय, मात्रा...)",sendMessage:"सन्देश पठाउनुहोस्",sending:"पठाउँदै...",messageSent:"सन्देश पठाइयो ✓",whatsappFarmer:"WhatsApp बाट किसानलाई सम्पर्क गर्नुहोस्",
  farmerDashboardTitle:"किसान ड्यासबोर्ड",myProducts:"मेरा उत्पादनहरू",addProduct:"नयाँ उत्पादन थप्नुहोस्",productName:"उत्पादनको नाम",productCategory:"श्रेणी",productPrice:"मूल्य (रु.)",productUnit:"एकाइ",productStock:"स्टक",productDescription:"विवरण",save:"सुरक्षित गर्नुहोस्",saving:"सुरक्षित हुँदैछ...",delete:"मेटाउनुहोस्",confirmDelete:"साँच्चै मेटाउने हो?",customerMessages:"ग्राहक सन्देशहरू",noMessagesYet:"अहिलेसम्म कुनै सन्देश छैन।",noProductsYet:"अहिलेसम्म कुनै उत्पादन थपिएको छैन।",about:"बारेमा",
  adminDashboardTitle:"एडमिन ड्यासबोर्ड",totalUsers:"जम्मा प्रयोगकर्ता",totalFarmers:"जम्मा किसान",totalCustomers:"जम्मा ग्राहक",totalProducts:"जम्मा उत्पादन",totalMessages:"जम्मा सन्देश",allUsers:"सबै प्रयोगकर्ताहरू",allProducts:"सबै उत्पादनहरू",name:"नाम",email:"इमेल",role:"भूमिका",actions:"कार्य",roleFarmer:"किसान",roleCustomer:"ग्राहक",roleAdmin:"एडमिन",
  cartTitle:"मेरो कार्ट",cartEmpty:"तपाईंको कार्ट खाली छ।",continueShopping:"किनमेल जारी राख्नुहोस्",subtotal:"उप-जम्मा",total:"जम्मा",proceedToCheckout:"चेकआउट गर्नुहोस्",choosePayment:"भुक्तानी विधि छान्नुहोस्",payCod:"डेलिभरीमा नगद (Cash on Delivery)",payEsewa:"eSewa",payKhalti:"Khalti",payCard:"डेबिट/क्रेडिट कार्ड",placeOrder:"अर्डर गर्नुहोस्",placingOrder:"अर्डर गर्दै...",orderSuccess:"तपाईंको अर्डर सफल भयो!",orderNumber:"अर्डर नम्बर",viewMyOrders:"मेरा अर्डरहरू हेर्नुहोस्",remove:"हटाउनुहोस्",
  myOrdersTitle:"मेरा अर्डरहरू",noOrdersYet:"तपाईंले अहिलेसम्म कुनै अर्डर गर्नुभएको छैन।",orderedOn:"अर्डर मिति",stagePlaced:"अर्डर राखियो",stageConfirmed:"किसानले पुष्टि गर्नुभयो",stageOutForDelivery:"डेलिभरीमा छ",stageDelivered:"डेलिभर भयो",trackOrder:"अर्डर ट्र्याक गर्नुहोस्",
  createAccount:"खाता खोल्नुहोस्",createAccountSubtitle:"सुरु गर्न आफ्नो खाता बनाउनुहोस्",iAmA:"म हुँ:",fullName:"पूरा नाम",fullNamePlaceholder:"आफ्नो पूरा नाम लेख्नुहोस्",choosePassword:"पासवर्ड बनाउनुहोस्",confirmPassword:"पासवर्ड पुष्टि गर्नुहोस्",confirmPasswordPlaceholder:"पासवर्ड फेरि लेख्नुहोस्",farmLocation:"फार्मको ठेगाना",farmLocationPlaceholder:"जस्तै: काभ्रेपलाञ्चोक, नेपाल",createAccountBtn:"खाता खोल्नुहोस्",creatingAccount:"खाता बन्दैछ...",alreadyHaveAccount:"पहिले नै खाता छ?",backToLogin:"लगइनमा फर्कनुहोस्",passwordMismatch:"पासवर्ड मेल खाएन",wrongRoleSelected:"यो खाता तपाईंले छानेको भूमिकासँग मेल खाँदैन।",adminLoginDetected:"एडमिन लगइन — भूमिका चयन आवश्यक छैन।",
  reply:"जवाफ दिनुहोस्",replyPlaceholder:"आफ्नो जवाफ लेख्नुहोस्...",sendReply:"जवाफ पठाउनुहोस्",replySent:"जवाफ पठाइयो ✓",myMessagesTitle:"मेरा सन्देशहरू",noConversationsYet:"अहिलेसम्म कुनै कुराकानी छैन।",you:"तपाईं",wishlistTitle:"मनपर्ने सूची",wishlistEmpty:"तपाईंको मनपर्ने सूची खाली छ।",showingCategory:"श्रेणी:",clearFilter:"फिल्टर हटाउनुहोस्",noProductsInCategory:"यो श्रेणीमा कुनै उत्पादन छैन।",myProfileTitle:"मेरो प्रोफाइल",profileName:"नाम",profileEmail:"इमेल",profileRole:"भूमिका",profileLocation:"ठेगाना",noLocationSet:"ठेगाना उल्लेख गरिएको छैन",sortBy:"क्रमबद्ध गर्नुहोस्",sortDefault:"डिफल्ट",sortPriceLow:"मूल्य: कम देखि बढी",sortPriceHigh:"मूल्य: बढी देखि कम",sortRating:"उच्च मूल्याङ्कन",priceRange:"मूल्य दायरा",minPrice:"न्यूनतम",maxPrice:"अधिकतम",applyFilter:"फिल्टर लागू गर्नुहोस्",noSearchResults:"कुनै नतिजा फेला परेन।",
  resetPasswordSubtitle:"तपाईंको ताजा Farm खाताको पासवर्ड रिसेट गर्नुहोस्।",getResetCode:"रिसेट कोड लिनुहोस्",resetCode:"रिसेट कोड",resetCodePlaceholder:"६ अंकको कोड",newPassword:"नयाँ पासवर्ड",changePassword:"पासवर्ड परिवर्तन गर्नुहोस्",email:"इमेल",language:"भाषा",nepali:"नेपाली",english:"English",switchLanguage:"भाषा परिवर्तन गर्नुहोस्",search:"खोज्नुहोस्",location:"स्थान",clearFilters:"फिल्टर हटाउनुहोस्",farmers:"किसानहरू",foods:"खानाहरू",noLocation:"स्थान छैन",newItem:"नयाँ",notifications:"सूचनाहरू",markAllRead:"सबै पढेको",noNotifications:"कुनै सूचना छैन।",cartLoading:"कार्ट लोड हुँदैछ...",waitingFarmer:"किसानको पुष्टि पर्खिरहेको छ",success:"सफल भयो",edit:"सम्पादन",cancel:"रद्द गर्नुहोस्",myFood:"मेरो खाना",orders:"अर्डरहरू",confirmOrder:"अर्डर पुष्टि गर्नुहोस्",soldStock:"बिकेको स्टक",totalSales:"कुल बिक्री",totalProfit:"कुल नाफा",foodEdit:"खाना सम्पादन",newFood:"नयाँ खाना थप्नुहोस्",foodName:"खानाको नाम",salePrice:"बिक्री मूल्य (रु/kg)",costPrice:"लागत मूल्य (रु/kg)",stockKg:"स्टक (kg)",foodDescription:"खानाको विवरण",foodPhoto:"खानाको फोटो",addFood:"खाना थप्नुहोस्",update:"अपडेट गर्नुहोस्",expiryDate:"म्याद सकिने मिति",deleteConfirm:"मेटाउनुहोस्",accept:"स्वीकार गर्नुहोस्",reject:"अस्वीकार गर्नुहोस्",farmerApproval:"किसान स्वीकृति",pendingFarmer:"कुनै pending farmer छैन।",deliveryStatus:"अर्डर / डेलिभरी स्थिति",waitingConfirmation:"किसानको पुष्टि पर्खिरहेको छ",users:"प्रयोगकर्ताहरू",approved:"स्वीकृत",pending:"पर्खिरहेको",adminDashboard:"एडमिन ड्यासबोर्ड",usersLabel:"प्रयोगकर्ता",foodsLabel:"खाना",ordersLabel:"अर्डर",pendingFarmers:"पर्खिरहेका किसान"
};

const EN = {
  ...NE,
  brandName:"Taja Farm",brandTagline:"From Farmers to Consumers",welcomeBack:"Welcome back!",loginSubtitle:"Login to continue",customer:"Customer",farmer:"Farmer",admin:"Admin",emailOrPhone:"Email or phone number",emailPlaceholder:"Enter your email or phone number",password:"Password",passwordPlaceholder:"Enter your password",forgotPassword:"Forgot password?",login:"Login",loggingIn:"Logging in...",demoAccountNote:"Demo accounts — Customer: customer@tajafarm.com / customer123 · Farmer: farmer@tajafarm.com / farmer123 · Admin: admin@tajafarm.com / admin123",noAccount:"Don't have an account?",signUp:"Sign up",areYouFarmer:"Are you a farmer?",registerHere:"Register here",heroTitle1:"From the farm",heroTitle2:"to your home",heroSubtitle:"Fresh, healthy and natural produce delivered directly from local farmers.",stat1Top:"100%",stat1Bottom:"Fresh",stat2Top:"Direct",stat2Bottom:"from farmers",stat3Top:"Healthy",stat3Bottom:"& natural",feat1:"100% Fresh",feat2:"Direct from farmers",feat3:"Healthy & natural",
  navHome:"Home",navOrders:"My Orders",navWishlist:"Wishlist",navProfile:"My Profile",navMessages:"Messages",navLogout:"Logout",searchPlaceholder:"Search vegetables, fruits, grains...",heroBannerTitle1:"Freshness you deserve,",heroBannerTitle2:"from farmers you trust",heroBannerSub:"Hand-picked, chemical-free and seasonal produce delivered to your door.",shopNow:"Shop Now",feature1Title:"Direct from farmers",feature1Sub:"No middlemen",feature2Title:"Fresh & quality",feature2Sub:"100% quality produce",feature3Title:"Secure payment",feature3Sub:"Safe and reliable",feature4Title:"Fast delivery",feature4Sub:"Delivered on time",shopByCategories:"Shop by Category",viewAll:"View all",topPicks:"Top picks for you",addToCart:"Add to Cart",added:"Added ✓",loadingProducts:"Loading products...",loadFailedNote:"— Is the backend running?",
  quantity:"Quantity",buyNow:"Buy Now",deliveredBy:"Delivered by",deliveryTime:"Delivery time",shipping:"Shipping",freeShippingNote:"Free on orders above Rs. 500",productDetails:"Product Details",aboutFarmer:"About the Farmer",viewFarmProfile:"View Farm Profile",alsoLike:"You may also like",badgeOrganic:"100% Organic",badgePesticideFree:"Pesticide Free",badgeHandPicked:"Hand Picked",badgeFreshNatural:"Fresh & Natural",category:"Category",price:"Price",stock:"Stock",stockAvailable:"available",loadingProduct:"Loading product...",home:"Home",localFarmer:"Local Farmer",contactFarmer:"Contact Farmer",messagePlaceholder:"Write your question here (e.g. delivery time, quantity...)",sendMessage:"Send Message",sending:"Sending...",messageSent:"Message sent ✓",whatsappFarmer:"Contact farmer on WhatsApp",
  farmerDashboardTitle:"Farmer Dashboard",myProducts:"My Products",addProduct:"Add New Product",productName:"Product Name",productCategory:"Category",productPrice:"Price (Rs.)",productUnit:"Unit",productStock:"Stock",productDescription:"Description",save:"Save",saving:"Saving...",delete:"Delete",confirmDelete:"Are you sure you want to delete this?",customerMessages:"Customer Messages",noMessagesYet:"No messages yet.",noProductsYet:"No products added yet.",about:"About",
  adminDashboardTitle:"Admin Dashboard",totalUsers:"Total Users",totalFarmers:"Total Farmers",totalCustomers:"Total Customers",totalProducts:"Total Products",totalMessages:"Total Messages",allUsers:"All Users",allProducts:"All Products",name:"Name",email:"Email",role:"Role",actions:"Actions",roleFarmer:"Farmer",roleCustomer:"Customer",roleAdmin:"Admin",cartTitle:"My Cart",cartEmpty:"Your cart is empty.",continueShopping:"Continue Shopping",subtotal:"Subtotal",total:"Total",proceedToCheckout:"Proceed to Checkout",choosePayment:"Choose Payment Method",payCod:"Cash on Delivery",payEsewa:"eSewa",payKhalti:"Khalti",payCard:"Debit/Credit Card",placeOrder:"Place Order",placingOrder:"Placing order...",orderSuccess:"Your order was successful!",orderNumber:"Order Number",viewMyOrders:"View My Orders",remove:"Remove",myOrdersTitle:"My Orders",noOrdersYet:"You haven't placed any orders yet.",orderedOn:"Ordered on",stagePlaced:"Order placed",stageConfirmed:"Confirmed by farmer",stageOutForDelivery:"Out for delivery",stageDelivered:"Delivered",trackOrder:"Track Order",
  createAccount:"Create Account",createAccountSubtitle:"Create your account to get started",iAmA:"I am a:",fullName:"Full Name",fullNamePlaceholder:"Enter your full name",choosePassword:"Create Password",confirmPassword:"Confirm Password",confirmPasswordPlaceholder:"Enter your password again",farmLocation:"Farm Location",farmLocationPlaceholder:"e.g. Kavrepalanchok, Nepal",createAccountBtn:"Create Account",creatingAccount:"Creating account...",alreadyHaveAccount:"Already have an account?",backToLogin:"Back to Login",passwordMismatch:"Passwords do not match",wrongRoleSelected:"This account does not match the selected role.",adminLoginDetected:"Admin login — no role selection is required.",reply:"Reply",replyPlaceholder:"Write your reply...",sendReply:"Send Reply",replySent:"Reply sent ✓",myMessagesTitle:"My Messages",noConversationsYet:"No conversations yet.",you:"You",wishlistTitle:"Wishlist",wishlistEmpty:"Your wishlist is empty.",showingCategory:"Category:",clearFilter:"Clear Filter",noProductsInCategory:"No products in this category.",myProfileTitle:"My Profile",profileName:"Name",profileEmail:"Email",profileRole:"Role",profileLocation:"Location",noLocationSet:"No location set",sortBy:"Sort by",sortDefault:"Default",sortPriceLow:"Price: Low to High",sortPriceHigh:"Price: High to Low",sortRating:"Highest Rated",priceRange:"Price Range",minPrice:"Minimum",maxPrice:"Maximum",applyFilter:"Apply Filter",noSearchResults:"No results found.",resetPasswordSubtitle:"Reset your Taja Farm account password.",getResetCode:"Get Reset Code",resetCode:"Reset Code",resetCodePlaceholder:"6-digit code",newPassword:"New Password",changePassword:"Change Password",email:"Email",language:"Language",nepali:"नेपाली",english:"English",switchLanguage:"Switch language",search:"Search",location:"Location",clearFilters:"Clear filters",farmers:"Farmers",foods:"Foods",noLocation:"No location",newItem:"New",notifications:"Notifications",markAllRead:"Mark all as read",noNotifications:"No notifications.",cartLoading:"Loading cart...",waitingFarmer:"Waiting for farmer confirmation",success:"Success",edit:"Edit",cancel:"Cancel",myFood:"My Food",orders:"Orders",confirmOrder:"Confirm Order",soldStock:"Stock sold",totalSales:"Total sales",totalProfit:"Total profit",foodEdit:"Edit food",newFood:"Add new food",foodName:"Food name",salePrice:"Sale price (Rs/kg)",costPrice:"Cost price (Rs/kg)",stockKg:"Stock (kg)",foodDescription:"Food description",foodPhoto:"Food photo",addFood:"Add Food",update:"Update",expiryDate:"Expiry Date",deleteConfirm:"Delete",accept:"Accept",reject:"Reject",farmerApproval:"Farmer Approval",pendingFarmer:"No pending farmers.",deliveryStatus:"Order / Delivery Status",waitingConfirmation:"Waiting for farmer confirmation",users:"Users",approved:"Approved",pending:"Pending",adminDashboard:"Admin Dashboard",usersLabel:"Users",foodsLabel:"Foods",ordersLabel:"Orders",pendingFarmers:"Pending farmers"
};

export let currentLanguage = localStorage.getItem("taja_language") || "ne";
export const t = { ...NE };
function applyLanguage(){
  const source = currentLanguage === "en" ? EN : NE;
  Object.keys(t).forEach(k=>delete t[k]);
  Object.assign(t, source);
}
export function setLanguage(lang){
  currentLanguage = lang === "en" ? "en" : "ne";
  localStorage.setItem("taja_language", currentLanguage);
  applyLanguage();
  window.dispatchEvent(new CustomEvent("taja-language-changed", { detail: currentLanguage }));
}
export function toggleLanguage(){ setLanguage(currentLanguage === "en" ? "ne" : "en"); }
applyLanguage();

export const CATEGORY_NE={Vegetables:"तरकारी",Fruits:"फलफूल",Dairy:"दुग्ध पदार्थ",Grains:"अन्न",Pulses:"दलहन",Organic:"जैविक","Leafy Greens":"हरियो सागपात"};
export const CATEGORY_EN={Vegetables:"Vegetables",Fruits:"Fruits",Dairy:"Dairy",Grains:"Grains",Pulses:"Pulses",Organic:"Organic","Leafy Greens":"Leafy Greens"};
export const PRODUCT_NE={"Organic Tomato":"जैविक गोलभेडा",Cucumber:"काँक्रो",Potato:"आलु",Carrot:"गाजर"};
export function categoryLabel(name){ return currentLanguage === "en" ? (CATEGORY_EN[name]||name) : (CATEGORY_NE[name]||name); }
export function productLabel(name){ return currentLanguage === "en" ? name : (PRODUCT_NE[name]||name); }
